### ISSUE TITLE
Hi! There seems a typo in src/checkInput.cpp

### ISSUE THREAD

**Issue by LovEinstein** [buaazhouxingyu/topoana#3]
It says this when I am doing "make": 
src/checkInput.cpp:75:26: fatal error: use of undeclared identifier 'eaccess'; did you mean 'access'? 
Just a reminder. Thanks for your nice topoana package!

**Comment by buaazhouxingyu** [comment]
Hi @LovEinstein, 

Thank you very much for the kind reminder. I am sorry for the lateness of my response. 

**Upon the information you provided, I have revised "eaccess" to "access" in the last commit I just made.**  

By the way, "eaccess" is not a typo. It works on the servers I used. In the related header file ``/usr/include/unistd.h``, I found the definition of ``eaccess`` in the following codes:
```
/* Test for access to NAME using the real UID and real GID.  */
extern int access (__const char *__name, int __type) __THROW __nonnull ((1));

#ifdef __USE_GNU
/* Test for access to NAME using the effective UID and GID
   (as normal file operations use).  */
extern int euidaccess (__const char *__name, int __type)
     __THROW __nonnull ((1));

/* An alias for `euidaccess', used by some other systems.  */
extern int eaccess (__const char *__name, int __type)
     __THROW __nonnull ((1));
#endif
``` 
So I think there might be some differences related to the codes in the systems we used.

Thanks again for the feedback! Please let me know whenever you find any problems on the program.
